Fix 1 - FieldInfo object has no attribute type_
I am pushing 2 different solutions for the  API error:
`AttributeError: 'FieldInfo' object has no attribute 'type_'`

I do not know which is desirable in the new Forge setup.

This PR gets the same values that previous WebUIs (A1111, old Forge, etc) would get from using `request.__fields__[field.api].type_`

- The `type_` attribute is now replaced with `annotation`
- However, `annotation` returns a typing construct (like Optional[str])
- This PR extracts the type from the annotation